modLoader = "javafml"
loaderVersion = "[40,)"
license = "GNU-AGPL-3.0-only"
[[mods]]
modId = "compromise"
version = "${file.jarVersion}"
displayName = "Compromise"
authors = "Tapio"
description = "Adding Flexible Multilingual Support to Minecraft!"